# .travis.yml - configuration file for the travis continuous integration service
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# PHP versions to test against.
# See: http://docs.travis-ci.com/user/languages/php/
php:
  - 5.6
  - 7.1

install:
  - composer install
script:
  - python -mjson.tool composer.json
after_install:
  - composer show
